const PK_BUILD='0.3.0-github';
const state={front:null,identified:null,token:null,bootstrap:null,session:null,lane:null,deviceId:null,bulk:false,student:null,studentDetails:null,basket:[],laneValues:{},currentPrinter:null,recentJobs:[],pendingReprint:null,detentionAvailability:null,requestDeliveryMode:'AUTO',requestDeliveryPeriod:'',requestWhen:'',detentionDate:'',camera:{stream:null,raf:null,lastCode:'',lastAt:0}};
document.addEventListener('DOMContentLoaded',init);

async function init(){
  state.deviceId=getDeviceId();
  try{
    await PassKioskBridge.ready();
    state.front=await server('getFrontDoorConfig');
  }catch(err){
    toast(err.message||'PassKiosk backend is not available.',true,7000);
  }
  document.getElementById('usernameInput').focus();
}
function getDeviceId(){const k='PassKioskDeviceId';let id=localStorage.getItem(k);if(!id){id=(window.crypto&&crypto.randomUUID)?crypto.randomUUID():'PKD-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(k,id)}return id}
function server(fn,...args){return PassKioskBridge.call(fn,...args)}

async function identifyUser(){
  const input=document.getElementById('usernameInput');clearInvalid(input);
  try{const res=await server('identifyAdult',input.value);if(!res.ok)throw new Error(res.message||'User not found.');state.identified=res;document.getElementById('welcomeText').textContent='Welcome '+res.displayName;document.getElementById('identifyPane').classList.add('hidden');document.getElementById('printerPane').classList.remove('hidden');renderFrontPrinters()}catch(err){markInvalid(input);toast(err.message,true)}
}
function renderFrontPrinters(){const box=document.getElementById('frontPrinters'),remembered=localStorage.getItem('PassKioskLastPrinter:'+state.identified.username)||'';box.innerHTML='';(state.front.printers||[]).forEach(p=>{const b=document.createElement('button');b.className='printer-btn'+(p.key===remembered?' remembered':'');b.textContent=p.friendlyName;b.onclick=()=>enterPassKiosk(p.key);box.appendChild(b)})}
async function enterPassKiosk(printerKey){try{const res=await server('startSession',state.identified.username,printerKey,state.deviceId);state.token=res.token;state.currentPrinter=res.printer;localStorage.setItem('PassKioskLastPrinter:'+state.identified.username,printerKey);state.bootstrap=await server('getBootstrapData',state.token);state.session=state.bootstrap.session;initializeLaneValues();document.getElementById('front').classList.add('hidden');document.getElementById('app').classList.remove('hidden');updateContext();selectLane(null)}catch(err){toast(err.message,true)}}
function resetFrontDoor(){state.identified=null;document.getElementById('usernameInput').value='';document.getElementById('identifyPane').classList.remove('hidden');document.getElementById('printerPane').classList.add('hidden');document.getElementById('usernameInput').focus()}
function initializeLaneValues(){const me=state.session.username,loc=state.session.defaultLocation||'';state.laneValues={PASS:{from:loc},RQST:{destination:loc,requestedByUsername:me},DET:{issuedByUsername:me,reportTo:state.bootstrap.detention.afterSchool.defaultLocation||''},LUNCH_DET:{issuedByUsername:me,reportTo:state.bootstrap.detention.lunch.defaultLocation||''},BUS:{approvedByUsername:me}}}
function updateContext(){const a=state.bootstrap.adults.find(x=>x.username===state.session.username);document.getElementById('contextUser').textContent=a?a.displayName:state.session.displayName;document.getElementById('contextPrinter').textContent=state.currentPrinter?state.currentPrinter.friendlyName:''}

function selectLane(lane){state.lane=lane;state.bulk=false;state.student=null;state.studentDetails=null;state.basket=[];state.detentionAvailability=null;state.requestDeliveryMode='AUTO';state.requestDeliveryPeriod='';state.requestWhen='';state.detentionDate='';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.lane===lane));const w=document.getElementById('workspace');if(!lane){w.className='pick-lane';w.innerHTML='↑ Pick a lane';return}w.className='';if(lane==='PASS')renderPass();if(lane==='RQST')renderRequest();if(lane==='DET')renderDetention(false);if(lane==='LUNCH_DET')renderDetention(true);if(lane==='BUS')renderBus();if(lane==='SETTINGS')renderSettings()}
function refreshCurrentLane(){const keep=state.lane;if(keep==='PASS')renderPass();if(keep==='RQST')renderRequest();if(keep==='DET')renderDetention(false);if(keep==='LUNCH_DET')renderDetention(true);if(keep==='BUS')renderBus()}

function studentPickerHtml({allowBulk=true}={}){return `<div class="card"><div class="student-head"><div class="section-title" style="margin:0">FIND STUDENT</div>${allowBulk?`<button id="basketToggle" class="basket-toggle ${state.bulk?'active':''}" title="Bulk input" onclick="toggleBulk()">🧺</button>`:''}</div><div class="search-wrap"><input id="studentSearch" class="field student-search" placeholder="Name or Student Number" autocomplete="off" oninput="studentSearchChanged()" onkeydown="studentSearchKey(event)"><button class="camera-btn" title="Scan QR" onclick="openCamera()">📷</button><div id="studentSuggestions" class="suggestions hidden"></div></div><div id="selectedStudentArea"></div></div>`}
function toggleBulk(){state.bulk=!state.bulk;state.student=null;state.studentDetails=null;state.basket=[];state.requestDeliveryMode='AUTO';state.requestDeliveryPeriod='';refreshCurrentLane()}
function studentSearchChanged(){const input=document.getElementById('studentSearch');if(!input)return;const q=input.value.trim();if(!q){hideSuggestions();return}if(state.bulk&&looksLikeMultiIds(q)){addManyIds(q);input.value='';hideSuggestions();return}renderSuggestions(searchStudentIndex(q).slice(0,8))}
function studentSearchKey(e){if(e.key==='Escape')hideSuggestions();if(e.key==='Enter'&&state.bulk&&e.currentTarget.value.trim()){const exact=searchStudentIndex(e.currentTarget.value.trim());if(exact.length===1){e.preventDefault();chooseStudent(exact[0].studentId)}}}
function looksLikeMultiIds(text){if(!/[\n,\t ]/.test(text))return false;const bits=text.split(/[\s,\t\r\n]+/).filter(Boolean);return bits.length>1&&bits.every(x=>/^\d+$/.test(x))}
function addManyIds(text){const ids=text.split(/[\s,\t\r\n]+/).map(x=>x.trim()).filter(Boolean);let missing=0;ids.forEach(id=>{const s=(state.bootstrap.studentIndex||[]).find(x=>x.studentId===id);if(s)addStudentSelection(s,true);else missing++});if(missing)toast(missing+' student number'+(missing===1?' was':'s were')+' not found.',true);updateSelectedStudentArea()}
function searchStudentIndex(query){const q=normalizeSearch(query),tokens=q.split(/\s+/).filter(Boolean);return(state.bootstrap.studentIndex||[]).filter(s=>{const id=String(s.studentId||''),fn=normalizeSearch(s.firstName),ln=normalizeSearch(s.lastName),a=fn+' '+ln,b=ln+' '+fn;return tokens.every(t=>id.includes(t)||fn.includes(t)||ln.includes(t)||a.includes(t)||b.includes(t))})}
function normalizeSearch(s){return String(s||'').toLowerCase().replace(/[^\p{L}\p{N}\s'-]/gu,'').trim()}
function renderSuggestions(results){const box=document.getElementById('studentSuggestions');if(!box)return;if(!results.length){box.innerHTML='<div class="suggestion muted">No matching student</div>';box.classList.remove('hidden');return}box.innerHTML=results.map(s=>`<div class="suggestion" onclick="chooseStudent('${attr(s.studentId)}')"><span><strong>${esc(s.firstName)} ${esc(s.lastName)}</strong><br><span class="small muted">${esc(s.studentId)}</span></span><span class="pill">Grade ${esc(s.grade)}</span></div>`).join('');box.classList.remove('hidden')}
function hideSuggestions(){const b=document.getElementById('studentSuggestions');if(b)b.classList.add('hidden')}
async function chooseStudent(studentId){const s=(state.bootstrap.studentIndex||[]).find(x=>x.studentId===String(studentId));if(!s)return;await addStudentSelection(s,false);const input=document.getElementById('studentSearch');if(input)input.value='';hideSuggestions()}
async function addStudentSelection(s,silentDuplicate){if(state.bulk){if(state.basket.some(x=>x.studentId===s.studentId)){if(!silentDuplicate)toast('Already in basket');return}state.basket.push(s);updateSelectedStudentArea();if(state.lane==='DET'||state.lane==='LUNCH_DET')await loadDetentionAvailability();return}state.student=s;try{const details=await server('getStudentDetails',state.token,s.studentId);if(!details.ok)throw new Error(details.message||'Student lookup failed.');state.studentDetails=details;updateSelectedStudentArea();afterStudentSelected()}catch(err){toast(err.message,true)}}
function removeStudent(studentId){if(state.bulk)state.basket=state.basket.filter(x=>x.studentId!==studentId);else{state.student=null;state.studentDetails=null}updateSelectedStudentArea();afterStudentSelected()}
function updateSelectedStudentArea(){const box=document.getElementById('selectedStudentArea');if(!box)return;if(state.bulk){if(!state.basket.length){box.innerHTML='<div class="small muted" style="margin-top:8px">Bulk mode — add students by search, pasted IDs, or repeated QR scans.</div>';return}box.innerHTML='<div class="basket-list">'+state.basket.map(s=>`<div class="basket-item"><span><strong>${esc(s.firstName)} ${esc(s.lastName)}</strong> <span class="muted small">${esc(s.studentId)}</span></span><button class="xbtn" onclick="removeStudent('${attr(s.studentId)}')">×</button></div>`).join('')+'</div>';return}if(!state.student){box.innerHTML='';return}box.innerHTML=`<div class="student-card"><div><div class="student-name">${esc(state.student.firstName)} ${esc(state.student.lastName)}</div><div class="small muted">${esc(state.student.studentId)} · Grade ${esc(state.student.grade)}</div></div><button class="xbtn" onclick="removeStudent('${attr(state.student.studentId)}')">×</button></div>`}
